### ISSUE TITLE
Server is unable to make an AP

### ISSUE THREAD

**Issue by nedimhx** [vbshightime/ESPMeshServer#1]
Hello, 

After uploading code I get this in console:

Setting soft-AP ... ssid: ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮
Password: ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮
⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮
⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮

**Comment by vbshightime** [comment]
Here we are running our device in AP mode for 30 sec during setup. We have hosted a web server where you have to enter the user credentials within this 30 secs. The web server is being hosted at 192.168. 1.4. device will fetch these credentials and save it in EEPROM and when you have to connect to your local wifi, it will fetch these credentials from EEPROM and connects to the localWiFi. Are you following the same procedure. There might be the case that it is not reading or writing the correct value to EEPROM.

**Comment by nedimhx** [comment]
@vbshightime I didn't notify that AP is created, and yes problem was that eeprom is empty becouse I didn't connected to AP and enter wifi details. Now it's working and I'm testing it :)
